name: publish-PyPI CD

on:
  workflow_run:
    workflows: ["metadata-extractor CI"]
    branches: [master]
    types: 
      - completed

jobs:
  release:
    steps:
    - name: Publish package to PyPI
      env:
        VERSION: ${{ github.event.release.tag_name }}
        USERNAME: __token__
        PASSWORD: ${{ secrets.PYPI_APIKEY }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
